//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountCodeDetail
    {
        public int ID { get; set; }
        public Nullable<int> DiscountCodeID { get; set; }
        public string Code { get; set; }
        public Nullable<bool> IsUsed { get; set; }
    
        public virtual DiscountCode DiscountCode { get; set; }
    }
}
