//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportCouponDetail
    {
        public int ID { get; set; }
        public int ImportCouponID { get; set; }
        public int ProductID { get; set; }
        public int Price { get; set; }
        public int Quantity { get; set; }
    
        public virtual ImportCoupon ImportCoupon { get; set; }
        public virtual Product Product { get; set; }
    }
}
