//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public System.DateTime DateOrder { get; set; }
        public System.DateTime DateShip { get; set; }
        public int Offer { get; set; }
        public bool IsPaid { get; set; }
        public bool IsCancel { get; set; }
        public bool IsDelete { get; set; }
        public bool IsDelivere { get; set; }
        public bool IsApproved { get; set; }
        public bool IsReceived { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
