//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ToyStore2021Entities : DbContext
    {
        public ToyStore2021Entities()
            : base("name=ToyStore2021Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessTimesCount> AccessTimesCounts { get; set; }
        public virtual DbSet<Age> Ages { get; set; }
        public virtual DbSet<Decentralization> Decentralizations { get; set; }
        public virtual DbSet<DiscountCode> DiscountCodes { get; set; }
        public virtual DbSet<DiscountCodeDetail> DiscountCodeDetails { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<ImportCoupon> ImportCoupons { get; set; }
        public virtual DbSet<ImportCouponDetail> ImportCouponDetails { get; set; }
        public virtual DbSet<ItemCart> ItemCarts { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Producer> Producers { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<ProductCategoryParent> ProductCategoryParents { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductViewed> ProductVieweds { get; set; }
        public virtual DbSet<QA> QAs { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserDiscountCode> UserDiscountCodes { get; set; }
        public virtual DbSet<UsersSpin> UsersSpins { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
    }
}
